flowchart AUTO
subgraph env_preprod[Preprod]
  subgraph preprod_AWS[AWS]
    tf_aws_cloudwatch_log_group_module_networking_main["aws_cloudwatch_log_group.module_networking__main"]
    tf_aws_eip_module_networking_nat_eip["aws_eip.module_networking__nat_eip"]
    tf_aws_flow_log_module_networking_main["aws_flow_log.module_networking__main"]
    tf_aws_iam_policy_module_networking_vpc_flow_logs_policy["aws_iam_policy.module_networking__vpc_flow_logs_policy"]
    tf_aws_iam_role_module_networking_vpc_flow_logs_role["aws_iam_role.module_networking__vpc_flow_logs_role"]
    tf_aws_iam_role_policy_attachment_module_networking_vpc_flow_logs_policy_attachment["aws_iam_role_policy_attachment.module_networking__vpc_flow_logs_policy_attachment"]
    tf_aws_internet_gateway_module_networking_main["aws_internet_gateway.module_networking__main"]
    tf_aws_kms_key_module_kms_key["aws_kms_key.module_kms__key"]
    tf_aws_nat_gateway_module_networking_main["aws_nat_gateway.module_networking__main"]
    tf_aws_route_module_networking_private_nat_gateway["aws_route.module_networking__private_nat_gateway"]
    tf_aws_route_module_networking_public_internet_gateway["aws_route.module_networking__public_internet_gateway"]
    tf_aws_route_table_module_networking_private["aws_route_table.module_networking__private"]
    tf_aws_route_table_module_networking_public["aws_route_table.module_networking__public"]
    tf_aws_route_table_association_module_networking_private["aws_route_table_association.module_networking__private"]
    tf_aws_route_table_association_module_networking_private_2["aws_route_table_association.module_networking__private_2"]
    tf_aws_route_table_association_module_networking_public["aws_route_table_association.module_networking__public"]
    tf_aws_route_table_association_module_networking_public_2["aws_route_table_association.module_networking__public_2"]
    tf_aws_s3_bucket_module_sagemaker_projects_bucket_bucket["aws_s3_bucket.module_sagemaker_projects_bucket__bucket"]
    tf_aws_s3_bucket_lifecycle_configuration_module_sagemaker_projects_bucket_artifacts_lifecycle["aws_s3_bucket_lifecycle_configuration.module_sagemaker_projects_bucket__artifacts_lifecycle"]
    tf_aws_s3_bucket_policy_module_sagemaker_projects_bucket_bucket["aws_s3_bucket_policy.module_sagemaker_projects_bucket__bucket"]
    tf_aws_s3_bucket_public_access_block_module_sagemaker_projects_bucket_bucket["aws_s3_bucket_public_access_block.module_sagemaker_projects_bucket__bucket"]
    tf_aws_s3_bucket_server_side_encryption_configuration_module_sagemaker_projects_bucket_bucket["aws_s3_bucket_server_side_encryption_configuration.module_sagemaker_projects_bucket__bucket"]
    tf_aws_s3_bucket_versioning_module_sagemaker_projects_bucket_bucket["aws_s3_bucket_versioning.module_sagemaker_projects_bucket__bucket"]
    tf_aws_security_group_module_networking_main["aws_security_group.module_networking__main"]
    tf_aws_ssm_parameter_module_kms_kms_key["aws_ssm_parameter.module_kms__kms_key"]
    tf_aws_ssm_parameter_module_networking_private_subnet_id["aws_ssm_parameter.module_networking__private_subnet_id"]
    tf_aws_ssm_parameter_module_networking_sg_id["aws_ssm_parameter.module_networking__sg_id"]
    tf_aws_subnet_module_networking_private["aws_subnet.module_networking__private"]
    tf_aws_subnet_module_networking_private_2["aws_subnet.module_networking__private_2"]
    tf_aws_subnet_module_networking_public["aws_subnet.module_networking__public"]
    tf_aws_subnet_module_networking_public_2["aws_subnet.module_networking__public_2"]
    tf_aws_vpc_module_networking_main["aws_vpc.module_networking__main"]
    tf_aws_vpc_endpoint_module_networking_events["aws_vpc_endpoint.module_networking__events"]
    tf_aws_vpc_endpoint_module_networking_logs["aws_vpc_endpoint.module_networking__logs"]
    tf_aws_vpc_endpoint_module_networking_s3["aws_vpc_endpoint.module_networking__s3"]
    tf_aws_vpc_endpoint_module_networking_sagemaker_api["aws_vpc_endpoint.module_networking__sagemaker_api"]
    tf_aws_vpc_endpoint_module_networking_sagemaker_runtime["aws_vpc_endpoint.module_networking__sagemaker_runtime"]
    tf_aws_vpc_endpoint_module_networking_sagemaker_studio["aws_vpc_endpoint.module_networking__sagemaker_studio"]
    tf_aws_vpc_endpoint_module_networking_service_catalog["aws_vpc_endpoint.module_networking__service_catalog"]
    tf_aws_vpc_endpoint_module_networking_sts["aws_vpc_endpoint.module_networking__sts"]
  end
end
subgraph env_shared[Shared]
  subgraph shared_AWS[AWS]
    tf_aws_cloudwatch_log_group_main["aws_cloudwatch_log_group.main"]
    tf_aws_eip_nat_eip["aws_eip.nat_eip"]
    tf_aws_flow_log_main["aws_flow_log.main"]
    tf_aws_internet_gateway_main["aws_internet_gateway.main"]
    tf_aws_kms_key_key["aws_kms_key.key"]
    tf_aws_nat_gateway_main["aws_nat_gateway.main"]
    tf_aws_route_private_nat_gateway["aws_route.private_nat_gateway"]
    tf_aws_route_public_internet_gateway["aws_route.public_internet_gateway"]
    tf_aws_route_table_private["aws_route_table.private"]
    tf_aws_route_table_public["aws_route_table.public"]
    tf_aws_route_table_association_private["aws_route_table_association.private"]
    tf_aws_route_table_association_private_2["aws_route_table_association.private_2"]
    tf_aws_route_table_association_public["aws_route_table_association.public"]
    tf_aws_route_table_association_public_2["aws_route_table_association.public_2"]
    tf_aws_s3_bucket_bucket["aws_s3_bucket.bucket"]
    tf_aws_s3_bucket_lifecycle_configuration_artifacts_lifecycle["aws_s3_bucket_lifecycle_configuration.artifacts_lifecycle"]
    tf_aws_s3_bucket_policy_bucket["aws_s3_bucket_policy.bucket"]
    tf_aws_s3_bucket_public_access_block_bucket["aws_s3_bucket_public_access_block.bucket"]
    tf_aws_s3_bucket_server_side_encryption_configuration_bucket["aws_s3_bucket_server_side_encryption_configuration.bucket"]
    tf_aws_s3_bucket_versioning_bucket["aws_s3_bucket_versioning.bucket"]
    tf_aws_sagemaker_domain_sagemaker_domain["aws_sagemaker_domain.sagemaker_domain"]
    tf_aws_sagemaker_servicecatalog_portfolio_status_enable_sagemaker_servicecatalog_portfolio["aws_sagemaker_servicecatalog_portfolio_status.enable_sagemaker_servicecatalog_portfolio"]
    tf_aws_sagemaker_user_profile_data_scientist_sagemaker_user_profiles["aws_sagemaker_user_profile.data_scientist_sagemaker_user_profiles"]
    tf_aws_sagemaker_user_profile_lead_data_scientist_sagemaker_user_profiles["aws_sagemaker_user_profile.lead_data_scientist_sagemaker_user_profiles"]
    tf_aws_security_group_main["aws_security_group.main"]
    tf_aws_subnet_private["aws_subnet.private"]
    tf_aws_subnet_private_2["aws_subnet.private_2"]
    tf_aws_subnet_public["aws_subnet.public"]
    tf_aws_subnet_public_2["aws_subnet.public_2"]
    tf_aws_vpc_main["aws_vpc.main"]
  end
end
tf_aws_cloudwatch_log_group_main --> tf_aws_flow_log_main
tf_aws_cloudwatch_log_group_module_networking_main --> tf_aws_flow_log_module_networking_main
tf_aws_eip_module_networking_nat_eip --> tf_aws_nat_gateway_module_networking_main
tf_aws_eip_nat_eip --> tf_aws_nat_gateway_main
tf_aws_iam_policy_module_networking_vpc_flow_logs_policy --> tf_aws_iam_role_policy_attachment_module_networking_vpc_flow_logs_policy_attachment
tf_aws_iam_role_module_networking_vpc_flow_logs_role --> tf_aws_flow_log_module_networking_main
tf_aws_iam_role_module_networking_vpc_flow_logs_role --> tf_aws_iam_role_policy_attachment_module_networking_vpc_flow_logs_policy_attachment
tf_aws_internet_gateway_main --> tf_aws_route_public_internet_gateway
tf_aws_internet_gateway_module_networking_main --> tf_aws_route_module_networking_public_internet_gateway
tf_aws_kms_key_module_kms_key --> tf_aws_ssm_parameter_module_kms_kms_key
tf_aws_nat_gateway_main --> tf_aws_route_private_nat_gateway
tf_aws_nat_gateway_module_networking_main --> tf_aws_route_module_networking_private_nat_gateway
tf_aws_route_table_module_networking_private --> tf_aws_route_module_networking_private_nat_gateway
tf_aws_route_table_module_networking_private --> tf_aws_route_table_association_module_networking_private
tf_aws_route_table_module_networking_private --> tf_aws_route_table_association_module_networking_private_2
tf_aws_route_table_module_networking_public --> tf_aws_route_module_networking_public_internet_gateway
tf_aws_route_table_module_networking_public --> tf_aws_route_table_association_module_networking_public
tf_aws_route_table_module_networking_public --> tf_aws_route_table_association_module_networking_public_2
tf_aws_route_table_private --> tf_aws_route_private_nat_gateway
tf_aws_route_table_private --> tf_aws_route_table_association_private
tf_aws_route_table_private --> tf_aws_route_table_association_private_2
tf_aws_route_table_public --> tf_aws_route_public_internet_gateway
tf_aws_route_table_public --> tf_aws_route_table_association_public
tf_aws_route_table_public --> tf_aws_route_table_association_public_2
tf_aws_s3_bucket_bucket --> tf_aws_s3_bucket_lifecycle_configuration_artifacts_lifecycle
tf_aws_s3_bucket_bucket --> tf_aws_s3_bucket_policy_bucket
tf_aws_s3_bucket_bucket --> tf_aws_s3_bucket_public_access_block_bucket
tf_aws_s3_bucket_bucket --> tf_aws_s3_bucket_server_side_encryption_configuration_bucket
tf_aws_s3_bucket_bucket --> tf_aws_s3_bucket_versioning_bucket
tf_aws_s3_bucket_module_sagemaker_projects_bucket_bucket --> tf_aws_s3_bucket_lifecycle_configuration_module_sagemaker_projects_bucket_artifacts_lifecycle
tf_aws_s3_bucket_module_sagemaker_projects_bucket_bucket --> tf_aws_s3_bucket_policy_module_sagemaker_projects_bucket_bucket
tf_aws_s3_bucket_module_sagemaker_projects_bucket_bucket --> tf_aws_s3_bucket_public_access_block_module_sagemaker_projects_bucket_bucket
tf_aws_s3_bucket_module_sagemaker_projects_bucket_bucket --> tf_aws_s3_bucket_server_side_encryption_configuration_module_sagemaker_projects_bucket_bucket
tf_aws_s3_bucket_module_sagemaker_projects_bucket_bucket --> tf_aws_s3_bucket_versioning_module_sagemaker_projects_bucket_bucket
tf_aws_sagemaker_domain_sagemaker_domain --> tf_aws_sagemaker_user_profile_data_scientist_sagemaker_user_profiles
tf_aws_sagemaker_domain_sagemaker_domain --> tf_aws_sagemaker_user_profile_lead_data_scientist_sagemaker_user_profiles
tf_aws_security_group_module_networking_main --> tf_aws_ssm_parameter_module_networking_sg_id
tf_aws_security_group_module_networking_main --> tf_aws_vpc_endpoint_module_networking_events
tf_aws_security_group_module_networking_main --> tf_aws_vpc_endpoint_module_networking_logs
tf_aws_security_group_module_networking_main --> tf_aws_vpc_endpoint_module_networking_sagemaker_api
tf_aws_security_group_module_networking_main --> tf_aws_vpc_endpoint_module_networking_sagemaker_runtime
tf_aws_security_group_module_networking_main --> tf_aws_vpc_endpoint_module_networking_sagemaker_studio
tf_aws_security_group_module_networking_main --> tf_aws_vpc_endpoint_module_networking_service_catalog
tf_aws_security_group_module_networking_main --> tf_aws_vpc_endpoint_module_networking_sts
tf_aws_subnet_module_networking_private --> tf_aws_route_table_association_module_networking_private
tf_aws_subnet_module_networking_private --> tf_aws_ssm_parameter_module_networking_private_subnet_id
tf_aws_subnet_module_networking_private --> tf_aws_vpc_endpoint_module_networking_events
tf_aws_subnet_module_networking_private --> tf_aws_vpc_endpoint_module_networking_logs
tf_aws_subnet_module_networking_private --> tf_aws_vpc_endpoint_module_networking_sagemaker_api
tf_aws_subnet_module_networking_private --> tf_aws_vpc_endpoint_module_networking_sagemaker_runtime
tf_aws_subnet_module_networking_private --> tf_aws_vpc_endpoint_module_networking_sagemaker_studio
tf_aws_subnet_module_networking_private --> tf_aws_vpc_endpoint_module_networking_service_catalog
tf_aws_subnet_module_networking_private --> tf_aws_vpc_endpoint_module_networking_sts
tf_aws_subnet_module_networking_private_2 --> tf_aws_route_table_association_module_networking_private_2
tf_aws_subnet_module_networking_private_2 --> tf_aws_ssm_parameter_module_networking_private_subnet_id
tf_aws_subnet_module_networking_private_2 --> tf_aws_vpc_endpoint_module_networking_events
tf_aws_subnet_module_networking_private_2 --> tf_aws_vpc_endpoint_module_networking_logs
tf_aws_subnet_module_networking_private_2 --> tf_aws_vpc_endpoint_module_networking_sagemaker_api
tf_aws_subnet_module_networking_private_2 --> tf_aws_vpc_endpoint_module_networking_sagemaker_runtime
tf_aws_subnet_module_networking_private_2 --> tf_aws_vpc_endpoint_module_networking_sagemaker_studio
tf_aws_subnet_module_networking_private_2 --> tf_aws_vpc_endpoint_module_networking_service_catalog
tf_aws_subnet_module_networking_private_2 --> tf_aws_vpc_endpoint_module_networking_sts
tf_aws_subnet_module_networking_public --> tf_aws_nat_gateway_module_networking_main
tf_aws_subnet_module_networking_public --> tf_aws_route_table_association_module_networking_public
tf_aws_subnet_module_networking_public_2 --> tf_aws_route_table_association_module_networking_public_2
tf_aws_subnet_private --> tf_aws_route_table_association_private
tf_aws_subnet_private_2 --> tf_aws_route_table_association_private_2
tf_aws_subnet_public --> tf_aws_nat_gateway_main
tf_aws_subnet_public --> tf_aws_route_table_association_public
tf_aws_subnet_public_2 --> tf_aws_route_table_association_public_2
tf_aws_vpc_main --> tf_aws_flow_log_main
tf_aws_vpc_main --> tf_aws_internet_gateway_main
tf_aws_vpc_main --> tf_aws_route_table_private
tf_aws_vpc_main --> tf_aws_route_table_public
tf_aws_vpc_main --> tf_aws_security_group_main
tf_aws_vpc_main --> tf_aws_subnet_private
tf_aws_vpc_main --> tf_aws_subnet_private_2
tf_aws_vpc_main --> tf_aws_subnet_public
tf_aws_vpc_main --> tf_aws_subnet_public_2
tf_aws_vpc_module_networking_main --> tf_aws_flow_log_module_networking_main
tf_aws_vpc_module_networking_main --> tf_aws_internet_gateway_module_networking_main
tf_aws_vpc_module_networking_main --> tf_aws_route_table_module_networking_private
tf_aws_vpc_module_networking_main --> tf_aws_route_table_module_networking_public
tf_aws_vpc_module_networking_main --> tf_aws_security_group_module_networking_main
tf_aws_vpc_module_networking_main --> tf_aws_subnet_module_networking_private
tf_aws_vpc_module_networking_main --> tf_aws_subnet_module_networking_private_2
tf_aws_vpc_module_networking_main --> tf_aws_subnet_module_networking_public
tf_aws_vpc_module_networking_main --> tf_aws_subnet_module_networking_public_2
tf_aws_vpc_module_networking_main --> tf_aws_vpc_endpoint_module_networking_events
tf_aws_vpc_module_networking_main --> tf_aws_vpc_endpoint_module_networking_logs
tf_aws_vpc_module_networking_main --> tf_aws_vpc_endpoint_module_networking_s3
tf_aws_vpc_module_networking_main --> tf_aws_vpc_endpoint_module_networking_sagemaker_api
tf_aws_vpc_module_networking_main --> tf_aws_vpc_endpoint_module_networking_sagemaker_runtime
tf_aws_vpc_module_networking_main --> tf_aws_vpc_endpoint_module_networking_sagemaker_studio
tf_aws_vpc_module_networking_main --> tf_aws_vpc_endpoint_module_networking_service_catalog
tf_aws_vpc_module_networking_main --> tf_aws_vpc_endpoint_module_networking_sts
